# Generated by Django 5.0.1 on 2025-04-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_options_remove_blog_target_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('academic', 'Academic')], default='professional', max_length=20),
        ),
    ]
