# Generated by Django 5.0.1 on 2025-04-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_tone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_title',
        ),
    ]
