# Generated by Django 5.0.1 on 2025-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blog_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reference_documents',
            field=models.ManyToManyField(blank=True, related_name='referenced_in_blogs', to='core.document'),
        ),
    ]
