# Generated by Django 5.0.1 on 2025-04-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog_reference_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user_keywords',
            new_name='target_keywords',
        ),
    ]
