# Generated by Django 5.0.1 on 2025-04-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_user_keywords_blog_target_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='seo_score',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='word_count',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='target_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('formal', 'Formal')], default='professional', max_length=20),
        ),
    ]
